name: coverage
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
permissions: {}
jobs:
  coverage:
    permissions:
      contents: read
      code-quality: write
      pull-requests: read # not sure if this is required
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: stable
    - name: Calculate coverage
      run: |
        go test -count=1 -v -covermode=atomic -coverprofile=cover.out -coverpkg=./... ./...
    - name: Convert Go coverage profile to cobertuba format
      run: |
        go install github.com/boumenot/gocover-cobertura@v1.5.0
        gocover-cobertura < cover.out > cover.xml
    - name: Upload coverage to GitHub API
      uses: actions/upload-code-coverage@d8e329117199404bba6fc81efe8093dc7c015e34 # v1.4.2
      with:
        file: cover.xml
        language: Go
        label: code-coverage/go-test
        # feature only available for team and enterprise accounts
        fail-on-error: false
